# Site settings
author: Jesse Neumann
title: 15 Weeks to Professional Data Scientist
header-img: img/home-bg.png
email: jesseneumann@gmail.com
copyright_name: Jesse Neumann
description: > # this means to ignore newlines until "baseurl:"
  The Journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Jesse989

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
